#!/usr/bin/env bash

split() {
    # Usage: split "string" "delimiter" "field"
    IFS=$'\n' read -d "" -ra arr <<< "${1//$2/$'\n'}"
    printf '%s\n' "${arr[$3]}"
}

id=$1

 while IFS= read -r node; do
    node="$(split "$node" " " 3)"

    if [[ "$node" == "$id" ]]; then
        tabbedsub_parentpx=$(pgrep -fo "tabbed-sub $id")

        if [[ -n $tabbedsub_parentpx ]]; then
            tabbedsub_px=$(pgrep -P "$tabbedsub_parentpx")
            kill "$tabbedsub_px"
        fi
        exit 0
    fi
done < <(bspc subscribe node_remove)
