#!/usr/bin/env bash

id=$1

bspc subscribe node_remove | while read node; do
    node=$(echo $node | cut -d ' ' -f4)

    if [[ "$node" == "$id" ]]; then
        tabbedsub_px=$(pgrep -P $(pgrep -fo "tabbed-sub $id") -f "bspc")
        kill $tabbedsub_px
        exit 0
    fi
done
