#!/usr/bin/env bash

id=$1

bspc subscribe node_add | while read node; do
    node=$(echo $node | cut -d ' ' -f5)

    [[ -z $(bspc query -N -n $node.!floating) ]] && continue

    if [[ "$(bspc query -N $node -n @brother)" == "$id" ]]; then
        bspc config -n $node border_width 0
        xdotool windowreparent $node $id
    fi
done
