#!/usr/bin/env bash

split() {
    # Usage: split "string" "delimiter" "field"
    IFS=$'\n' read -d "" -ra arr <<< "${1//$2/$'\n'}"
    printf '%s\n' "${arr[$3]}"
}

id=$1

 while IFS= read -r node; do
    node="$(split "$node" " " 4)"

    bspc query -N -n "$node".tiled &> /dev/null || continue

    if [[ "$(bspc query -N "$node" -n @brother)" == "$id" ]]; then
        bspc config -n "$node" border_width 0
        xdotool windowreparent "$node" "$id"
    fi
done < <(bspc subscribe node_add)
